[package]
name = "gummy_benchmarks"
version = "0.1.0"
authors = [
    "Alice Cecile <alice.i.cecile@gmail.com>",
    "Johnathan Kelley <jkelleyrtp@gmail.com>",
]
edition = "2021"
description = "Benchmarks for the gummy crate"
repository = "https://github.com/RetGui/gummy"
keywords = ["cross-platform", "layout", "benchmarks"]
categories = ["gui", "benchmarks"]
license = "MIT"

[dependencies]
criterion = "0.7"
rand = { version = "0.9" }
rand_chacha = "0.9"
gummy = { path = ".." }
upstream_03 = { package = "taffy", version = "0.3", optional = true }
yoga = { version = "0.5.0", optional = true }
ordered-float = { version = "4", optional = true }
slotmap = { version = "1.0.6", optional = true }
parley = "0.7"

[features]
yoga = ["dep:yoga", "dep:slotmap", "dep:ordered-float"]
yoga-super-deep = ["yoga"]
upstream03 = ["dep:upstream_03"]
content_size = ["gummy/content_size"]
strict_provenance = ["gummy/strict_provenance"]
small = []
large = []

[[bench]]
name = "tree_creation"
path = "benches/tree_creation.rs"
harness = false

[[bench]]
name = "flexbox"
path = "benches/flexbox.rs"
harness = false

[[bench]]
name = "grid"
path = "benches/grid.rs"
harness = false

[[bench]]
name = "mixed"
path = "benches/mixed.rs"
harness = false
